# build_titles_catalog.py
#
# Rebuilds data/titles_catalog.csv with a clean, well-formed CSV.
# Run with:
#   python build_titles_catalog.py

from pathlib import Path
import pandas as pd

data = [
    {
        "title": "Harry Potter and the Sorcerer's Stone",
        "type": "film",
        "franchise_group": "Harry Potter",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 671,
    },
    {
        "title": "Harry Potter and the Chamber of Secrets",
        "type": "film",
        "franchise_group": "Harry Potter",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 672,
    },
    {
        "title": "Harry Potter and the Prisoner of Azkaban",
        "type": "film",
        "franchise_group": "Harry Potter",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 673,
    },
    {
        "title": "Harry Potter and the Goblet of Fire",
        "type": "film",
        "franchise_group": "Harry Potter",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 674,
    },
    {
        "title": "Harry Potter and the Order of the Phoenix",
        "type": "film",
        "franchise_group": "Harry Potter",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 675,
    },
    {
        "title": "Harry Potter and the Half-Blood Prince",
        "type": "film",
        "franchise_group": "Harry Potter",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 767,
    },
    {
        "title": "Harry Potter and the Deathly Hallows: Part 1",
        "type": "film",
        "franchise_group": "Harry Potter",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 12444,
    },
    {
        "title": "Harry Potter and the Deathly Hallows: Part 2",
        "type": "film",
        "franchise_group": "Harry Potter",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 12445,
    },
    {
        "title": "Fantastic Beasts and Where to Find Them",
        "type": "film",
        "franchise_group": "Harry Potter",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 259316,
    },
    {
        "title": "Game of Thrones",
        "type": "series",
        "franchise_group": "Game of Thrones",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 1399,
    },
    {
        "title": "House of the Dragon",
        "type": "series",
        "franchise_group": "Game of Thrones",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 94997,
    },
    {
        "title": "The Dark Knight",
        "type": "film",
        "franchise_group": "DC Universe",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 155,
    },
    {
        "title": "The Batman",
        "type": "film",
        "franchise_group": "DC Universe",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 414906,
    },
    {
        "title": "Man of Steel",
        "type": "film",
        "franchise_group": "DC Universe",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 49521,
    },
    {
        "title": "Wonder Woman",
        "type": "film",
        "franchise_group": "DC Universe",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 297762,
    },
    {
        "title": "Aquaman",
        "type": "film",
        "franchise_group": "DC Universe",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 297802,
    },
    {
        "title": "Justice League",
        "type": "film",
        "franchise_group": "DC Universe",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 141052,
    },
    {
        "title": "Dune",
        "type": "film",
        "franchise_group": "Dune",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 438631,
    },
    {
        "title": "Dune: Part Two",
        "type": "film",
        "franchise_group": "Dune",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 693134,
    },
    {
        "title": "Friends",
        "type": "series",
        "franchise_group": "Friends",
        "owner": "Warner Bros",
        "current_platform": "Netflix/Max",
        "tmdb_id": 1668,
    },
    {
        "title": "The Big Bang Theory",
        "type": "series",
        "franchise_group": "The Big Bang Theory",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 1418,
    },
    {
        "title": "Six Feet Under",
        "type": "series",
        "franchise_group": "Six Feet Under",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 1431,
    },
    {
        "title": "Westworld",
        "type": "series",
        "franchise_group": "Westworld",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 63247,
    },
    {
        "title": "Succession",
        "type": "series",
        "franchise_group": "Succession",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 76331,
    },
    {
        "title": "True Detective",
        "type": "series",
        "franchise_group": "True Detective",
        "owner": "Warner Bros",
        "current_platform": "Max",
        "tmdb_id": 46648,
    },
    {
        "title": "The Lord of the Rings: The Fellowship of the Ring",
        "type": "film",
        "franchise_group": "LOTR",
        "owner": "Warner Bros",
        "current_platform": "Netflix/Max",
        "tmdb_id": 120,
    },
    {
        "title": "The Lord of the Rings: The Two Towers",
        "type": "film",
        "franchise_group": "LOTR",
        "owner": "Warner Bros",
        "current_platform": "Netflix/Max",
        "tmdb_id": 121,
    },
    {
        "title": "The Lord of the Rings: The Return of the King",
        "type": "film",
        "franchise_group": "LOTR",
        "owner": "Warner Bros",
        "current_platform": "Netflix/Max",
        "tmdb_id": 122,
    },
]

df = pd.DataFrame(data)
data_dir = Path("data")
data_dir.mkdir(parents=True, exist_ok=True)
out_path = data_dir / "titles_catalog.csv"
df.to_csv(out_path, index=False)
print(f"[done] Wrote {len(df)} rows to {out_path}")
